In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
from scripts.Simplex import Simplex
from sympy import *

# Simplex

In [3]:
np.set_printoptions(suppress=True)
init_printing() 


A = np.array([[-1,1],[1,2],[2,-3],[-1,0],[0,-1]])
b = np.array([1,8,2,0,0]).reshape(-1, 1)
c = np.array([2,1]).reshape(1, -1)

start = np.array([2,3]).reshape(1, -1)
s = Simplex(A, b, c, start)
s.run()

# Iteration 1

<IPython.core.display.Latex object>

## Step 1

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Math object>

<IPython.core.display.Latex object>

## Step 2

<IPython.core.display.Latex object>

## Step 3

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

## Step 4, getting index with smallest column value

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

## Step 5 - get direction

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

## Step 6

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

## Step 7

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

## Step 8

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

# Iteration 1

<IPython.core.display.Latex object>

## Step 1

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Math object>

<IPython.core.display.Latex object>

## Step 2

<IPython.core.display.Latex object>

## Step 3

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

Finished


# Optimization

In [18]:
from scripts.Newton_GradDesc import OptimizLibrary
import numpy as np
from sympy import *


x, y = symbols('x y')
# Function
fun = (2*x - y**2)**2+(y-2-x)**2

# Starting point
x0 = np.array([0, 0])

In [19]:
df_x = fun.diff(x)
df_y = fun.diff(y)
df2_xx = df_x.diff(x)
df2_xy = df_x.diff(y)
df2_yx = df_y.diff(x)
df2_yy = df_y.diff(y)

def f(point):
    return float(fun.evalf(subs={x: point[0], y: point[1]}))


def dx(point):
    return float(df_x.evalf(subs={x: point[0], y: point[1]}))


def dy(point):
    return float(df_y.evalf(subs={x: point[0], y: point[1]}))


def dxdx(point):
    return float(df2_xx.evalf(subs={x: point[0], y: point[1]}))


def dydy(point):
    return float(df2_yy.evalf(subs={x: point[0], y: point[1]}))


def dxdy(point):
    return float(df2_xy.evalf(subs={x: point[0], y: point[1]}))

In [20]:
opt = OptimizLibrary(x0=x0, f=f, dx=dx, dy=dy, dxdx=dxdx, dydy=dydy, dxdy=dxdy)

In [21]:
"""
Gradient Descent
mode: step(always needed), parabola
"""
display(fun)
print(df_x)
print(df_y)
print(df2_xx)
print(df2_yy)
print(df2_xy)
print(df2_yx)

print("\n\nGradient Descent:")
opt.grad_descent(n=1, mode="step")

10*x - 4*y**2 - 2*y + 4
-2*x - 4*y*(2*x - y**2) + 2*y - 4
10
-8*x + 12*y**2 + 2
-8*y - 2
-8*y - 2


Gradient Descent:
β = 1.0 = 1:
([0 0] - 1.0 * [ 4. -4.]) = [-4.  4.]
612.0 !< 4.0

β = 0.5 = 1/2:
([0 0] - 0.5 * [ 4. -4.]) = [-2.  2.]
68.0 !< 4.0

β = 0.25 = 1/4:
([0 0] - 0.25 * [ 4. -4.]) = [-1.  1.]
9.0 !< 4.0

β = 0.125 = 1/8:
([0 0] - 0.125 * [ 4. -4.]) = [-0.5  0.5]
2.5625 !< 4.0

2.5625 < 4.0 done!
x_1 = x_0 - β * ∇_f(x_0) =
= ([0 0] - 0.125 * [ 4. -4.])
= [-0.5  0.5]
Result is (x_i y_i)^2 = [-0.5  0.5]^T with function value = 2.5625


array([-0.5,  0.5])

In [22]:
print("\n\nGradient Descent with parabola fitting:")
opt.grad_descent(n=1, mode="parabola")



Gradient Descent with parabola fitting:
β = 1.0 = 1:
([0 0] - 1.0 * [ 4. -4.]) = [-4.  4.]
612.0 !< 4.0

β = 0.5 = 1/2:
([0 0] - 0.5 * [ 4. -4.]) = [-2.  2.]
68.0 !< 4.0

β = 0.25 = 1/4:
([0 0] - 0.25 * [ 4. -4.]) = [-1.  1.]
9.0 !< 4.0

β = 0.125 = 1/8:
([0 0] - 0.125 * [ 4. -4.]) = [-0.5  0.5]
2.5625 !< 4.0

2.5625 < 4.0 done!
x_1 = x_0 - β * ∇_f(x_0) =
= ([0 0] - 0.125 * [ 4. -4.])
= [-0.5  0.5]
Result is (x_i y_i)^2 = [-0.5  0.5]^T with function value = 2.5625

Parabola fitting
P0 = self.f([0 0] - (0 * 0.125) * [ 4. -4.]) = 4.0
PB = self.f([0 0] - 0.125 * [ 4. -4.]) = 2.5625
P2B = self.f([0 0] - (2 * 0.125) * [ 4. -4.]) = 9.0

β^* = 0.08531746031746032 = (0.125 / 2) * (3 * 4.0 - 4 * 2.5625 + 9.0) / (4.0 - 2 * 2.5625 + 9.0)

x_1 = x_0 - β^* * ∇_f(x_0) =
= ([0 0] - 0.08531746031746032 * [ 4. -4.]) = [-0.34126984  0.34126984]
Result is (x_i y_i)^2 = [-0.34126984  0.34126984]^T with function value = 2.374110337891397


array([-0.34126984,  0.34126984])

In [23]:
"""
Newton
Only for 1 or 2 dimemsions
"""
#display(hessian(fun, [x, y]).subs(x,0).subs(y,0).inv())
print("\n\nNewton:")
opt.newton(n=1, dim=2)  # Only for 1 or 2 dim



Newton:
Initialize x_0 = [0 0]
Iteration 0
x_1 = x_0 - H_f([0 0])^-1 * ∇_f(x_0) =
= ([0 0] - [[0.125 0.125]
 [0.125 0.625]] * [ 4. -4.]) 
= [-0.  2.]
Result is (x_i y_i)^2 = [-0.  2.]^T


array([-0.,  2.])

In [25]:
"""
Broyden
Note that n=1 means 2 iterations (first iteration is Newton and second is Broyden)
"""
print("Broyden:")
opt.broyden(n=1)

Broyden:
Initialize x_0 = [0 0]
First iteration with Newton method
x_1 = x_0 - H_f([0 0])^-1 * ∇_f(x_0) =
= ([0 0] - [[0.125 0.125]
 [0.125 0.625]] * [ 4. -4.]) 
= [-0.  2.]
Broyden's method iteration 1
A_0^-1 = [[0.125 0.125]
 [0.125 0.625]]
g_1 = ∇_f(x_1) - ∇_f(x_0) = [-16.  32.] - [ 4. -4.] = [-20.  36.]
d_1 = x_1 - x_0 = [-0.  2.] - [0 0] = [-0.  2.]
A_2^-1 = A_1^-1 - (A_1^-1 * g_1 - d_1) * d_1^T * A_1^-1 / (d_1^T * A_1^-1 * g_1) = [[0.1125 0.0625]
 [0.0125 0.0625]]
x_2 = x_1 - A_1^-1 * ∇_f(x_1) = [-0.2  0.2] with function value f(x_2) = 2.753599999999997


In [11]:
"""
Aitken’s acceleration method
See example here to get x_i, x_i1, x_i2 correct:
i   x^i   Aitken y^1
0   100   -
1   10    -
2   2     1.21951
3   0.5   0.15384
"""
print("\n\nAitken:")
opt.aitken(x_i=2, x_i1=10, x_i2=100)



Aitken:
Result for y_i is = 1.2195121951219512
